x-environment: &shared-environment
  #-----------------------------------------------
  #-----------   EXCHANGES URLS   ----------------
  #-----------------------------------------------
  BIANCE_URL:  "wss://fstream.binance.com/ws"
  COINBASE_URL: "wss://ws-feed.exchange.coinbase.com"
  DERIBIT_URL: "wss://www.deribit.com/ws/api/v2"
  OKX_URL: "wss://ws.okx.com:8443/ws/v5/public"

  #-----------------------------------------------
  #-----------------   KAFKA     -----------------
  #-----------------------------------------------
  KAFKA_BROKER: "kafka:9092"
  KAFKA_NUM_PARTITIONS: "1"
  KAFKA_REPLICATION_FACTOR: "1"
  KAFKA_RETENTION_MS: "604800000"
  KAFKA_CLEANUP_POLICY: "delete"
  KAFKA_COMPRESSION_TYPE: "lz4"
  KAFKA_MIN_INSYNC_REPLICAS: "1"
  KAFKA_GROUP_ID: "price_service"

services:
  kafka:
    image: bitnami/kafka:3.8.0
    ports:
      - 9094:9094
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    # volumes:
    #   - ./volumes/kafka:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - app-network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8088:8080
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: price_service
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - app-network

  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 5173:4173
    networks:
      - app-network

  apis:
    container_name: apis
    build:
      context: ./apis
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    networks:
      - app-network

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   #command: ["sh", "-c", "while true; do echo 'Waiting'; sleep 5; done"]
  #   command: ["python", "main.py"]
  #   environment:
  #     <<: *shared-environment
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge